import type { AudioState, ParametricFilter } from '@/types/audio';

export interface ParsedConfig {
  preamp: number;
  filters: ParametricFilter[];
  graphicEQ: Record<string, number> | null;
  device: string | null;
  channel: string | null;
  rawLines: string[];
}

export class EQEngine {
  static parseConfig(configString: string): ParsedConfig {
    const lines = (configString || '').split(/\r?\n/);
    const result: ParsedConfig = {
      preamp: 0,
      filters: [],
      graphicEQ: null,
      device: null,
      channel: null,
      rawLines: []
    };

    for (let line of lines) {
      line = line.trim();
      if (!line) continue;

      if (line.startsWith('Preamp:')) {
        const match = line.match(/Preamp:\s*([-\d.,]+)\s*dB/i);
        if (match && match[1]) result.preamp = parseFloat(match[1].replace(',', '.'));
      } else if (line.startsWith('GraphicEQ:')) {
        result.graphicEQ = {};
        const points = line.substring(10).split(';');
        for (const point of points) {
          const parts = point.trim().split(/\s+/);
          if (parts.length >= 2 && parts[0] && parts[1]) {
            result.graphicEQ[parts[0].replace(',', '.')] = parseFloat(parts[1].replace(',', '.'));
          }
        }
      } else if (line.startsWith('Filter')) {
        const filterMatch = line.match(/Filter\s+(\d+):\s+(ON|OFF)\s+([A-Z0-9]+)\s+Fc\s+([\d.,]+)\s*Hz\s+Gain\s+([-\d.,]+)\s*dB\s+Q\s+([\d.,]+)/i);
        if (filterMatch && filterMatch[2] && filterMatch[3] && filterMatch[4] && filterMatch[5] && filterMatch[6]) {
          result.filters.push({
            id: `filter-${filterMatch[1]}`,
            enabled: filterMatch[2].toUpperCase() === 'ON',
            type: filterMatch[3],
            freq: parseFloat(filterMatch[4].replace(',', '.')),
            gain: parseFloat(filterMatch[5].replace(',', '.')),
            q: parseFloat(filterMatch[6].replace(',', '.'))
          });
        } else {
          result.rawLines.push(line);
        }
      } else if (line.startsWith('Device:')) {
        result.device = line.substring(7).trim();
      } else if (line.startsWith('Channel:')) {
        result.channel = line.substring(8).trim();
      } else {
        result.rawLines.push(line);
      }
    }

    return result;
  }
  
  static generateConfig(state: AudioState): string {
    if (!state) return '';
    if (state.eqEnabled === false) {
      return '# Studio Audio EQ is disabled (Bypassed by Serenity Hub)\nStage: pre-mix\n';
    }
    const lines: string[] = [];

    lines.push('# Generated by Serenity Hub Audio EQ');
    
    if (state.devices && state.devices.length > 0 && !state.devices.includes('all')) {
      lines.push(`Device: ${state.devices.join('; ')}`);
    }
    
    if (state.channel && state.channel !== 'all') {
      lines.push(`Channel: ${state.channel}`);
    } else {
      lines.push('Channel: all');
    }

    let effectivePreamp = state.preamp || 0;
    
    if (state.loudnessGuard && state.bassBoost > 0) {
      effectivePreamp -= state.bassBoost * 0.35;
    }
    
    lines.push(`Preamp: ${effectivePreamp.toFixed(2)} dB`);

    if (state.mode === 'graphic' && state.graphicFilters) {
      lines.push(this.generateGraphicEQLine(state.graphicFilters));
    } else if (state.mode === 'parametric' && state.parametricFilters && state.parametricFilters.length > 0) {
      lines.push(...this.generateFilterLines(state.parametricFilters));
    }

    let extraIndex = (state.parametricFilters?.length || 0) + 1;
    
    if (state.bassBoost && state.bassBoost > 0) {
      lines.push(`Filter ${extraIndex++}: ON LS Fc 80 Hz Gain ${state.bassBoost.toFixed(1)} dB Q 0.71`);
    }
    if (state.trebleAir && state.trebleAir > 0) {
      lines.push(`Filter ${extraIndex++}: ON HS Fc 12000 Hz Gain ${state.trebleAir.toFixed(1)} dB Q 0.71`);
    }

    if (state.crossfeed) {
      lines.push('# Headphone Crossfeed Active (Spatial width naturalizer)');
      lines.push(`Filter ${extraIndex++}: ON HS Fc 700 Hz Gain -1.8 dB Q 0.60`);
    }

    // Stereo Balance Handling (Equalizer APO Channel Attenuation)
    if (typeof state.stereoBalance === 'number' && state.stereoBalance !== 0) {
      lines.push('# Stereo Balance');
      if (state.stereoBalance < 0) {
        // Panned to Left -> Attenuate Right
        const rightAtten = (Math.abs(state.stereoBalance) / 100) * 30; // Up to -30 dB
        lines.push('Channel: R');
        lines.push(`Preamp: -${rightAtten.toFixed(2)} dB`);
        lines.push('Channel: all');
      } else {
        // Panned to Right -> Attenuate Left
        const leftAtten = (state.stereoBalance / 100) * 30; // Up to -30 dB
        lines.push('Channel: L');
        lines.push(`Preamp: -${leftAtten.toFixed(2)} dB`);
        lines.push('Channel: all');
      }
    }
    
    return lines.join('\n');
  }
  
  static generateGraphicEQLine(bands: Record<number, number>): string {
    const points: string[] = [];
    const freqs = Object.keys(bands || {}).map(Number).sort((a, b) => a - b);
    for (const freq of freqs) {
      const gain = bands[freq] ?? 0;
      points.push(`${freq} ${gain.toFixed(1)}`);
    }
    return `GraphicEQ: ${points.join('; ')}`;
  }
  
  static generateFilterLines(filters: ParametricFilter[]): string[] {
    return (filters || []).map((f, i) => {
      const state = f.enabled ? 'ON' : 'OFF';
      return `Filter ${i + 1}: ${state} ${f.type} Fc ${Math.round(f.freq || 1000)} Hz Gain ${(f.gain || 0).toFixed(1)} dB Q ${(f.q || 1.41).toFixed(2)}`;
    });
  }

  static calculateFilterResponse(filter: ParametricFilter, frequency: number, sampleRate = 48000): number {
    if (!filter || !filter.type || frequency <= 0) return 0;

    const freq = Math.max(10, Math.min(24000, filter.freq || 1000));
    const w0 = (2 * Math.PI * freq) / sampleRate;
    const q = Math.max(0.01, filter.q || 1.41);
    const alpha = Math.sin(w0) / (2 * q);
    const A = Math.pow(10, (filter.gain || 0) / 40);

    let b0 = 1, b1 = 0, b2 = 0, a0 = 1, a1 = 0, a2 = 0;

    switch (filter.type.toUpperCase()) {
      case 'PK':
      case 'PEAK':
        b0 = 1 + alpha * A;
        b1 = -2 * Math.cos(w0);
        b2 = 1 - alpha * A;
        a0 = 1 + alpha / A;
        a1 = -2 * Math.cos(w0);
        a2 = 1 - alpha / A;
        break;
      case 'LS':
      case 'LSC':
      case 'LSQ':
        b0 = A * ((A + 1) - (A - 1) * Math.cos(w0) + 2 * Math.sqrt(A) * alpha);
        b1 = 2 * A * ((A - 1) - (A + 1) * Math.cos(w0));
        b2 = A * ((A + 1) - (A - 1) * Math.cos(w0) - 2 * Math.sqrt(A) * alpha);
        a0 = (A + 1) + (A - 1) * Math.cos(w0) + 2 * Math.sqrt(A) * alpha;
        a1 = -2 * ((A - 1) + (A + 1) * Math.cos(w0));
        a2 = (A + 1) + (A - 1) * Math.cos(w0) - 2 * Math.sqrt(A) * alpha;
        break;
      case 'HS':
      case 'HSC':
      case 'HSQ':
        b0 = A * ((A + 1) + (A - 1) * Math.cos(w0) + 2 * Math.sqrt(A) * alpha);
        b1 = -2 * A * ((A - 1) + (A + 1) * Math.cos(w0));
        b2 = A * ((A + 1) + (A - 1) * Math.cos(w0) - 2 * Math.sqrt(A) * alpha);
        a0 = (A + 1) - (A - 1) * Math.cos(w0) + 2 * Math.sqrt(A) * alpha;
        a1 = 2 * ((A - 1) - (A + 1) * Math.cos(w0));
        a2 = (A + 1) - (A - 1) * Math.cos(w0) - 2 * Math.sqrt(A) * alpha;
        break;
      case 'LP':
        b0 = (1 - Math.cos(w0)) / 2;
        b1 = 1 - Math.cos(w0);
        b2 = (1 - Math.cos(w0)) / 2;
        a0 = 1 + alpha;
        a1 = -2 * Math.cos(w0);
        a2 = 1 - alpha;
        break;
      case 'HP':
        b0 = (1 + Math.cos(w0)) / 2;
        b1 = -(1 + Math.cos(w0));
        b2 = (1 + Math.cos(w0)) / 2;
        a0 = 1 + alpha;
        a1 = -2 * Math.cos(w0);
        a2 = 1 - alpha;
        break;
      case 'NO':
      case 'NOTCH':
        b0 = 1;
        b1 = -2 * Math.cos(w0);
        b2 = 1;
        a0 = 1 + alpha;
        a1 = -2 * Math.cos(w0);
        a2 = 1 - alpha;
        break;
      case 'BP':
        b0 = alpha;
        b1 = 0;
        b2 = -alpha;
        a0 = 1 + alpha;
        a1 = -2 * Math.cos(w0);
        a2 = 1 - alpha;
        break;
      case 'AP':
      default:
        return 0;
    }

    b0 /= a0;
    b1 /= a0;
    b2 /= a0;
    a1 /= a0;
    a2 /= a0;

    const phi = (2 * Math.PI * frequency) / sampleRate;
    const numReal = b0 + b1 * Math.cos(phi) + b2 * Math.cos(2 * phi);
    const numImag = -(b1 * Math.sin(phi) + b2 * Math.sin(2 * phi));
    const denReal = 1 + a1 * Math.cos(phi) + a2 * Math.cos(2 * phi);
    const denImag = -(a1 * Math.sin(phi) + a2 * Math.sin(2 * phi));

    const magnitude = Math.sqrt((numReal * numReal + numImag * numImag) / (denReal * denReal + denImag * denImag));
    const gainDB = 20 * Math.log10(Math.max(1e-6, magnitude));
    
    return isNaN(gainDB) ? 0 : gainDB;
  }
  
  static calculateCombinedResponse(
    filters: ParametricFilter[] | undefined,
    frequency: number,
    preamp = 0,
    bassBoost = 0,
    trebleAir = 0,
    graphicFilters?: Record<number, number>,
    mode: 'graphic' | 'parametric' = 'parametric',
    sampleRate = 48000
  ): number {
    let totalGain = preamp || 0;

    if (mode === 'parametric' && filters && Array.isArray(filters)) {
      for (const filter of filters) {
        if (filter && filter.enabled) {
          totalGain += this.calculateFilterResponse(filter, frequency, sampleRate);
        }
      }
    } else if (mode === 'graphic' && graphicFilters && typeof graphicFilters === 'object') {
      const freqs = Object.keys(graphicFilters).map(Number).sort((a, b) => a - b);
      for (const f of freqs) {
        const g = graphicFilters[f] || 0;
        if (Math.abs(g) > 0.05) {
          totalGain += this.calculateFilterResponse({ enabled: true, type: 'PK', freq: f, gain: g, q: 1.41 }, frequency, sampleRate);
        }
      }
    }

    if (bassBoost > 0) {
      totalGain += this.calculateFilterResponse({ enabled: true, type: 'LS', freq: 80, gain: bassBoost, q: 0.71 }, frequency, sampleRate);
    }
    if (trebleAir > 0) {
      totalGain += this.calculateFilterResponse({ enabled: true, type: 'HS', freq: 12000, gain: trebleAir, q: 0.71 }, frequency, sampleRate);
    }

    return isNaN(totalGain) ? 0 : totalGain;
  }
  
  static getBands(count: number): number[] {
    switch (count) {
      case 5:
        return [60, 250, 1000, 4000, 16000];
      case 10:
        return [31, 63, 125, 250, 500, 1000, 2000, 4000, 8000, 16000];
      case 15:
        return [25, 40, 63, 100, 160, 250, 400, 630, 1000, 1600, 2500, 4000, 6300, 10000, 16000];
      case 20:
        return [20, 25, 31.5, 40, 50, 63, 80, 100, 125, 160, 200, 250, 315, 400, 500, 630, 800, 1000, 1250, 1600];
      case 31:
      default:
        return [20, 25, 31.5, 40, 50, 63, 80, 100, 125, 160, 200, 250, 315, 400, 500, 630, 800, 1000, 1250, 1600, 2000, 2500, 3150, 4000, 5000, 6300, 8000, 10000, 12500, 16000, 20000];
    }
  }
  
  static formatFrequency(freq: number): string {
    if (freq >= 1000) return (freq / 1000).toFixed(freq % 1000 === 0 ? 0 : 1) + ' kHz';
    return Math.round(freq) + ' Hz';
  }
}
