import type { AudioPreset } from '@/types/audio';

export const AUTOEQ_ATTRIBUTION = {
  name: 'AutoEq',
  author: 'Jaakko Pasanen',
  license: 'MIT License',
  url: 'https://github.com/jaakkopasanen/AutoEq',
};

export const BUILTIN_BRANDS = [
  'Tous',
  'Apple',
  'Sennheiser',
  'Sony',
  'Beyerdynamic',
  'Bose',
  'Audio-Technica',
  'AKG',
  'Hifiman',
  'Audeze',
  'Focal',
  'Moondrop',
  'Samsung',
  'SteelSeries',
  'HyperX',
  'Logitech',
  'Philips',
  'Shure',
  'Meze',
  'Genres & Gaming',
] as const;

export const BUILTIN_PRESETS: AudioPreset[] = [
  // ==========================================
  // APPLE & BEATS
  // ==========================================
  {
    id: 'autoeq-airpods-max',
    name: 'Apple AirPods Max',
    brand: 'Apple',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Correction acoustique Harman Target : neutralise le bas-médium et apporte un éclat naturel aux voix.',
    mode: 'parametric',
    preamp: -6.5,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 105, gain: 5.5, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 240, gain: -2.8, q: 1.41 },
      { id: '3', enabled: true, type: 'PK', freq: 1250, gain: 3.2, q: 1.8 },
      { id: '4', enabled: true, type: 'PK', freq: 3600, gain: -3.5, q: 2.5 },
      { id: '5', enabled: true, type: 'HS', freq: 10000, gain: 2.0, q: 0.71 },
    ],
  },
  {
    id: 'autoeq-airpods-pro-2',
    name: 'Apple AirPods Pro 2 (USB-C & Lightning)',
    brand: 'Apple',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Calibrage haute fidélité : élargissement de la scène sonore et clarté cristalline.',
    mode: 'parametric',
    preamp: -4.8,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 80, gain: 2.2, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 480, gain: -1.5, q: 1.2 },
      { id: '3', enabled: true, type: 'PK', freq: 2800, gain: 2.8, q: 1.9 },
      { id: '4', enabled: true, type: 'PK', freq: 6200, gain: -3.2, q: 3.0 },
      { id: '5', enabled: true, type: 'HS', freq: 11000, gain: 2.5, q: 0.71 },
    ],
  },
  {
    id: 'autoeq-airpods-3',
    name: 'Apple AirPods 3',
    brand: 'Apple',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Compensation de l’absence d’isolation passive avec renfort de sous-basses.',
    mode: 'parametric',
    preamp: -5.2,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 90, gain: 4.8, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 800, gain: -2.0, q: 1.4 },
      { id: '3', enabled: true, type: 'PK', freq: 3200, gain: 3.5, q: 2.0 },
      { id: '4', enabled: true, type: 'PK', freq: 7500, gain: -4.0, q: 2.8 },
      { id: '5', enabled: true, type: 'HS', freq: 12000, gain: 1.5, q: 0.71 },
    ],
  },
  {
    id: 'autoeq-beats-studio-pro',
    name: 'Beats Studio Pro',
    brand: 'Apple',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Adoucit les basses percutantes et équilibre le registre médium.',
    mode: 'parametric',
    preamp: -6.0,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 70, gain: -3.2, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 300, gain: 1.8, q: 1.41 },
      { id: '3', enabled: true, type: 'PK', freq: 2200, gain: 4.0, q: 1.6 },
      { id: '4', enabled: true, type: 'PK', freq: 5800, gain: -3.0, q: 2.2 },
      { id: '5', enabled: true, type: 'HS', freq: 10000, gain: 2.0, q: 0.71 },
    ],
  },

  // ==========================================
  // SENNHEISER
  // ==========================================
  {
    id: 'autoeq-sennheiser-hd600',
    name: 'Sennheiser HD 600',
    brand: 'Sennheiser',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Extension de sous-basses manquante sur le casque de référence studio ouvert.',
    mode: 'parametric',
    preamp: -6.8,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 65, gain: 6.2, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 200, gain: -1.8, q: 1.41 },
      { id: '3', enabled: true, type: 'PK', freq: 1300, gain: -1.2, q: 2.0 },
      { id: '4', enabled: true, type: 'PK', freq: 3400, gain: -2.0, q: 2.2 },
      { id: '5', enabled: true, type: 'HS', freq: 10000, gain: 1.8, q: 0.71 },
    ],
  },
  {
    id: 'autoeq-sennheiser-hd650',
    name: 'Sennheiser HD 650 / HD 6XX',
    brand: 'Sennheiser',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Compense la voile chaude légendaire et apporte une clarté moderne.',
    mode: 'parametric',
    preamp: -6.5,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 60, gain: 6.5, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 220, gain: -2.2, q: 1.2 },
      { id: '3', enabled: true, type: 'PK', freq: 3200, gain: 2.4, q: 1.8 },
      { id: '4', enabled: true, type: 'PK', freq: 5600, gain: -2.0, q: 2.5 },
      { id: '5', enabled: true, type: 'HS', freq: 9000, gain: 3.2, q: 0.71 },
    ],
  },
  {
    id: 'autoeq-sennheiser-hd560s',
    name: 'Sennheiser HD 560S',
    brand: 'Sennheiser',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Lisse le pic d’aigu à 5 kHz et enrichit les basses profondes.',
    mode: 'parametric',
    preamp: -5.0,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 80, gain: 4.5, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 1400, gain: 1.5, q: 1.8 },
      { id: '3', enabled: true, type: 'PK', freq: 4800, gain: -4.5, q: 3.2 },
      { id: '4', enabled: true, type: 'HS', freq: 11000, gain: 1.2, q: 0.71 },
    ],
  },
  {
    id: 'autoeq-sennheiser-hd800s',
    name: 'Sennheiser HD 800 S',
    brand: 'Sennheiser',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Sublime la scène sonore holographique en domptant le pic à 6 kHz.',
    mode: 'parametric',
    preamp: -7.2,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 75, gain: 6.8, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 1800, gain: 2.2, q: 1.6 },
      { id: '3', enabled: true, type: 'PK', freq: 5900, gain: -5.8, q: 3.5 },
      { id: '4', enabled: true, type: 'HS', freq: 10000, gain: -1.5, q: 0.71 },
    ],
  },
  {
    id: 'autoeq-sennheiser-momentum-4',
    name: 'Sennheiser Momentum 4 Wireless',
    brand: 'Sennheiser',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Nettoie les basses trop dominantes pour révéler les voix et les instruments.',
    mode: 'parametric',
    preamp: -5.8,
    parametricFilters: [
      { id: '1', enabled: true, type: 'PK', freq: 160, gain: -4.2, q: 1.1 },
      { id: '2', enabled: true, type: 'PK', freq: 1200, gain: 2.5, q: 1.8 },
      { id: '3', enabled: true, type: 'PK', freq: 3500, gain: 3.0, q: 2.0 },
      { id: '4', enabled: true, type: 'PK', freq: 6500, gain: -2.8, q: 2.4 },
    ],
  },

  // ==========================================
  // SONY
  // ==========================================
  {
    id: 'autoeq-sony-wh1000xm5',
    name: 'Sony WH-1000XM5',
    brand: 'Sony',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Éclaircit la signature sonore en réduisant l’effet de masque du bas-médium.',
    mode: 'parametric',
    preamp: -6.2,
    parametricFilters: [
      { id: '1', enabled: true, type: 'PK', freq: 190, gain: -4.8, q: 1.1 },
      { id: '2', enabled: true, type: 'PK', freq: 1100, gain: 3.2, q: 1.6 },
      { id: '3', enabled: true, type: 'PK', freq: 3200, gain: 4.5, q: 1.9 },
      { id: '4', enabled: true, type: 'PK', freq: 7200, gain: -3.6, q: 2.5 },
      { id: '5', enabled: true, type: 'HS', freq: 10000, gain: 2.2, q: 0.71 },
    ],
  },
  {
    id: 'autoeq-sony-wh1000xm4',
    name: 'Sony WH-1000XM4',
    brand: 'Sony',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Transforme le son chaud d’origine en rendu audiophile neutre et dynamique.',
    mode: 'parametric',
    preamp: -6.8,
    parametricFilters: [
      { id: '1', enabled: true, type: 'PK', freq: 220, gain: -5.5, q: 1.0 },
      { id: '2', enabled: true, type: 'PK', freq: 1050, gain: 3.5, q: 1.5 },
      { id: '3', enabled: true, type: 'PK', freq: 3000, gain: 4.8, q: 1.8 },
      { id: '4', enabled: true, type: 'PK', freq: 6800, gain: -4.0, q: 2.2 },
      { id: '5', enabled: true, type: 'HS', freq: 9500, gain: 2.5, q: 0.71 },
    ],
  },
  {
    id: 'autoeq-sony-wf1000xm5',
    name: 'Sony WF-1000XM5 (Écouteurs)',
    brand: 'Sony',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Rapprochement précis de la cible Harman IE pour les écouteurs phares Sony.',
    mode: 'parametric',
    preamp: -4.5,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 90, gain: 1.5, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 650, gain: -2.0, q: 1.4 },
      { id: '3', enabled: true, type: 'PK', freq: 2800, gain: 2.6, q: 1.7 },
      { id: '4', enabled: true, type: 'PK', freq: 5800, gain: -3.0, q: 2.8 },
    ],
  },
  {
    id: 'autoeq-sony-mdr7506',
    name: 'Sony MDR-7506 Studio',
    brand: 'Sony',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Adoucit les aigus agressifs de monitoring et rajoute du corps aux basses.',
    mode: 'parametric',
    preamp: -5.5,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 85, gain: 3.8, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 250, gain: 1.2, q: 1.41 },
      { id: '3', enabled: true, type: 'PK', freq: 4500, gain: -5.5, q: 2.8 },
      { id: '4', enabled: true, type: 'PK', freq: 8500, gain: -4.2, q: 2.4 },
    ],
  },

  // ==========================================
  // BEYERDYNAMIC
  // ==========================================
  {
    id: 'autoeq-beyerdynamic-dt770-80',
    name: 'Beyerdynamic DT 770 Pro (80 Ω)',
    brand: 'Beyerdynamic',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Atténuation du célèbre « Beyer Peak » à 6–8 kHz et linéarisation des basses.',
    mode: 'parametric',
    preamp: -6.0,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 60, gain: 2.5, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 200, gain: -2.8, q: 1.41 },
      { id: '3', enabled: true, type: 'PK', freq: 3500, gain: 3.2, q: 2.0 },
      { id: '4', enabled: true, type: 'PK', freq: 5900, gain: -6.5, q: 3.0 },
      { id: '5', enabled: true, type: 'PK', freq: 8400, gain: -4.8, q: 2.8 },
    ],
  },
  {
    id: 'autoeq-beyerdynamic-dt990-250',
    name: 'Beyerdynamic DT 990 Pro (250 Ω)',
    brand: 'Beyerdynamic',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Adoucissement drastique des aigus perçants pour une écoute sans fatigue.',
    mode: 'parametric',
    preamp: -7.5,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 70, gain: 5.5, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 220, gain: -2.5, q: 1.2 },
      { id: '3', enabled: true, type: 'PK', freq: 1200, gain: 1.8, q: 1.8 },
      { id: '4', enabled: true, type: 'PK', freq: 5800, gain: -7.5, q: 3.2 },
      { id: '5', enabled: true, type: 'PK', freq: 8800, gain: -6.2, q: 3.0 },
    ],
  },
  {
    id: 'autoeq-beyerdynamic-dt1990',
    name: 'Beyerdynamic DT 1990 Pro (Pads Balanced)',
    brand: 'Beyerdynamic',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Linéarité exceptionnelle pour mastering et mixage haute précision.',
    mode: 'parametric',
    preamp: -6.2,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 65, gain: 4.8, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 1500, gain: 1.5, q: 1.6 },
      { id: '3', enabled: true, type: 'PK', freq: 7200, gain: -6.8, q: 3.5 },
      { id: '4', enabled: true, type: 'HS', freq: 11000, gain: 1.0, q: 0.71 },
    ],
  },

  // ==========================================
  // BOSE
  // ==========================================
  {
    id: 'autoeq-bose-qc45',
    name: 'Bose QuietComfort 45 / QC SE',
    brand: 'Bose',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Tempère le pic aigu à 6 kHz et confère une sonorité plus équilibrée.',
    mode: 'parametric',
    preamp: -5.8,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 80, gain: 2.5, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 1200, gain: 2.2, q: 1.5 },
      { id: '3', enabled: true, type: 'PK', freq: 3500, gain: -2.0, q: 2.0 },
      { id: '4', enabled: true, type: 'PK', freq: 5800, gain: -5.2, q: 2.8 },
    ],
  },
  {
    id: 'autoeq-bose-qc-ultra',
    name: 'Bose QuietComfort Ultra Headphones',
    brand: 'Bose',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Harmonisation fine pour le dernier modèle haut de gamme à réduction de bruit.',
    mode: 'parametric',
    preamp: -5.0,
    parametricFilters: [
      { id: '1', enabled: true, type: 'PK', freq: 180, gain: -2.8, q: 1.2 },
      { id: '2', enabled: true, type: 'PK', freq: 1400, gain: 2.0, q: 1.6 },
      { id: '3', enabled: true, type: 'PK', freq: 4800, gain: -3.5, q: 2.2 },
      { id: '4', enabled: true, type: 'HS', freq: 10000, gain: 2.0, q: 0.71 },
    ],
  },

  // ==========================================
  // AUDIO-TECHNICA
  // ==========================================
  {
    id: 'autoeq-audiotechnica-m50x',
    name: 'Audio-Technica ATH-M50x',
    brand: 'Audio-Technica',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Équilibre les basses lourdes et ouvre la clarté des voix médiums.',
    mode: 'parametric',
    preamp: -5.5,
    parametricFilters: [
      { id: '1', enabled: true, type: 'PK', freq: 180, gain: -4.5, q: 1.2 },
      { id: '2', enabled: true, type: 'PK', freq: 450, gain: 2.0, q: 1.5 },
      { id: '3', enabled: true, type: 'PK', freq: 3200, gain: 3.5, q: 1.8 },
      { id: '4', enabled: true, type: 'PK', freq: 9500, gain: -4.8, q: 2.6 },
    ],
  },
  {
    id: 'autoeq-audiotechnica-r70x',
    name: 'Audio-Technica ATH-R70x',
    brand: 'Audio-Technica',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Casque ouvert de référence : extension des infra-basses et aération.',
    mode: 'parametric',
    preamp: -6.0,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 65, gain: 5.5, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 1200, gain: -1.2, q: 1.8 },
      { id: '3', enabled: true, type: 'PK', freq: 5500, gain: -2.5, q: 2.5 },
      { id: '4', enabled: true, type: 'HS', freq: 10000, gain: 2.0, q: 0.71 },
    ],
  },

  // ==========================================
  // HIFIMAN & AUDEZE (PLANAR MAGNETIC)
  // ==========================================
  {
    id: 'autoeq-hifiman-sundara',
    name: 'Hifiman Sundara (2020)',
    brand: 'Hifiman',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Apporte l’impact de basse dynamique aux transducteurs magnétiques planaires.',
    mode: 'parametric',
    preamp: -6.5,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 80, gain: 6.2, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 1800, gain: 1.8, q: 1.5 },
      { id: '3', enabled: true, type: 'PK', freq: 6000, gain: -3.2, q: 2.8 },
      { id: '4', enabled: true, type: 'PK', freq: 9000, gain: -2.5, q: 2.2 },
    ],
  },
  {
    id: 'autoeq-hifiman-edition-xs',
    name: 'Hifiman Edition XS',
    brand: 'Hifiman',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Sublime les médiums et apporte une assise chaleureuse.',
    mode: 'parametric',
    preamp: -5.8,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 75, gain: 4.8, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 1600, gain: 2.5, q: 1.6 },
      { id: '3', enabled: true, type: 'PK', freq: 5500, gain: -3.0, q: 2.4 },
    ],
  },
  {
    id: 'autoeq-audeze-maxwell',
    name: 'Audeze Maxwell (Gaming & Audiophile)',
    brand: 'Audeze',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Le meilleur casque gaming sans fil planar magnétisé avec profil studio Harman.',
    mode: 'parametric',
    preamp: -4.5,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 85, gain: 2.2, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 3200, gain: 2.5, q: 1.8 },
      { id: '3', enabled: true, type: 'PK', freq: 6800, gain: -2.8, q: 2.5 },
    ],
  },
  {
    id: 'autoeq-audeze-lcd-x',
    name: 'Audeze LCD-X (2021)',
    brand: 'Audeze',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Calibrage référence monitoring de mixage pour transducteurs Audeze 106mm.',
    mode: 'parametric',
    preamp: -6.5,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 80, gain: 3.5, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 3500, gain: 4.8, q: 1.6 },
      { id: '3', enabled: true, type: 'PK', freq: 5800, gain: -3.0, q: 2.5 },
    ],
  },

  // ==========================================
  // AKG & FOCAL
  // ==========================================
  {
    id: 'autoeq-akg-k371',
    name: 'AKG K371',
    brand: 'AKG',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Ajustements millimétrés sur le casque déjà très proche de la cible Harman.',
    mode: 'parametric',
    preamp: -3.5,
    parametricFilters: [
      { id: '1', enabled: true, type: 'PK', freq: 120, gain: -1.5, q: 1.4 },
      { id: '2', enabled: true, type: 'PK', freq: 3800, gain: 2.2, q: 2.0 },
      { id: '3', enabled: true, type: 'PK', freq: 7200, gain: -2.8, q: 2.5 },
    ],
  },
  {
    id: 'autoeq-focal-clear',
    name: 'Focal Clear (Open-Back)',
    brand: 'Focal',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Dynamique spectaculaire avec extension des sous-basses 20–60 Hz.',
    mode: 'parametric',
    preamp: -6.0,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 70, gain: 5.5, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 1400, gain: -1.5, q: 1.8 },
      { id: '3', enabled: true, type: 'PK', freq: 6000, gain: -3.0, q: 2.5 },
    ],
  },

  // ==========================================
  // MOONDROP & IEMS
  // ==========================================
  {
    id: 'autoeq-moondrop-blessing-3',
    name: 'Moondrop Blessing 3',
    brand: 'Moondrop',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Écouteurs hybrides 2DD+4BA : renfort des sous-basses et lissage des aigus.',
    mode: 'parametric',
    preamp: -4.0,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 100, gain: 3.5, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 6000, gain: -3.5, q: 3.0 },
    ],
  },
  {
    id: 'autoeq-moondrop-aria',
    name: 'Moondrop Aria / Chu II',
    brand: 'Moondrop',
    category: 'autoeq',
    author: 'AutoEq (Harman Target)',
    description: 'Calibrage d’excellence pour IEMs budgétaires ultra-populaires.',
    mode: 'parametric',
    preamp: -3.8,
    parametricFilters: [
      { id: '1', enabled: true, type: 'PK', freq: 250, gain: -1.8, q: 1.4 },
      { id: '2', enabled: true, type: 'PK', freq: 3800, gain: 2.0, q: 2.0 },
      { id: '3', enabled: true, type: 'PK', freq: 6500, gain: -3.0, q: 2.8 },
    ],
  },

  // ==========================================
  // GAMING HEADSETS
  // ==========================================
  {
    id: 'autoeq-steelseries-nova-pro',
    name: 'SteelSeries Arctis Nova Pro Wireless',
    brand: 'SteelSeries',
    category: 'gaming',
    author: 'AutoEq (Harman Target)',
    description: 'Atténue les résonances plastiques et clarifie le positionnement 3D spatial.',
    mode: 'parametric',
    preamp: -5.2,
    parametricFilters: [
      { id: '1', enabled: true, type: 'PK', freq: 180, gain: -3.5, q: 1.2 },
      { id: '2', enabled: true, type: 'PK', freq: 1200, gain: 2.8, q: 1.6 },
      { id: '3', enabled: true, type: 'PK', freq: 3500, gain: 3.5, q: 2.0 },
      { id: '4', enabled: true, type: 'PK', freq: 6500, gain: -4.0, q: 2.5 },
    ],
  },
  {
    id: 'autoeq-hyperx-cloud-2',
    name: 'HyperX Cloud II / Cloud Alpha',
    brand: 'HyperX',
    category: 'gaming',
    author: 'AutoEq (Harman Target)',
    description: 'Rapproche le casque gaming de la neutralité studio avec basses précises.',
    mode: 'parametric',
    preamp: -5.5,
    parametricFilters: [
      { id: '1', enabled: true, type: 'PK', freq: 220, gain: -3.8, q: 1.1 },
      { id: '2', enabled: true, type: 'PK', freq: 3200, gain: 3.2, q: 1.8 },
      { id: '3', enabled: true, type: 'PK', freq: 4500, gain: -4.2, q: 2.6 },
      { id: '4', enabled: true, type: 'HS', freq: 9500, gain: 2.0, q: 0.71 },
    ],
  },
  {
    id: 'autoeq-logitech-g-pro-x',
    name: 'Logitech G Pro X / G Pro X 2',
    brand: 'Logitech',
    category: 'gaming',
    author: 'AutoEq (Harman Target)',
    description: 'Supprime la bosse de 150 Hz et sublime les bruits de pas et rechargements.',
    mode: 'parametric',
    preamp: -5.0,
    parametricFilters: [
      { id: '1', enabled: true, type: 'PK', freq: 160, gain: -4.0, q: 1.2 },
      { id: '2', enabled: true, type: 'PK', freq: 1100, gain: 2.2, q: 1.6 },
      { id: '3', enabled: true, type: 'PK', freq: 3800, gain: 3.0, q: 2.0 },
      { id: '4', enabled: true, type: 'PK', freq: 7000, gain: -3.5, q: 2.5 },
    ],
  },

  // ==========================================
  // PROFILES MUSIQUE, GAMING & UTILITY
  // ==========================================
  {
    id: 'genre-basshead-extreme',
    name: 'Basshead Sub-Boost 20-80 Hz',
    brand: 'Genres & Gaming',
    category: 'genre',
    description: 'Gros impact sous-grave propre pour EDM, Trap, Hip-Hop sans noyer les voix.',
    mode: 'parametric',
    preamp: -5.0,
    bassBoost: 6.0,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 80, gain: 6.0, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 250, gain: -1.5, q: 1.41 },
      { id: '3', enabled: true, type: 'HS', freq: 10000, gain: 1.5, q: 0.71 },
    ],
  },
  {
    id: 'genre-pop-vocal-clarity',
    name: 'Pop & Voix Brillantes (V-Shape Moderne)',
    brand: 'Genres & Gaming',
    category: 'genre',
    description: 'Mise en avant éclatante des voix féminines et masculines avec percussion nette.',
    mode: 'parametric',
    preamp: -3.5,
    trebleAir: 3.0,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 100, gain: 3.5, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 800, gain: -1.8, q: 1.2 },
      { id: '3', enabled: true, type: 'PK', freq: 3200, gain: 4.0, q: 1.6 },
      { id: '4', enabled: true, type: 'HS', freq: 12000, gain: 3.0, q: 0.71 },
    ],
  },
  {
    id: 'gaming-fps-footsteps',
    name: 'FPS Footsteps Booster (Valorant / CS2 / CoD)',
    brand: 'Genres & Gaming',
    category: 'gaming',
    description: 'Isolation des fréquences clés de bruits de pas (1.5 kHz à 4 kHz) et tirs atténués.',
    mode: 'parametric',
    preamp: -4.0,
    parametricFilters: [
      { id: '1', enabled: true, type: 'HP', freq: 60, gain: 0, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 250, gain: -4.0, q: 1.41 },
      { id: '3', enabled: true, type: 'PK', freq: 2200, gain: 5.5, q: 1.8 },
      { id: '4', enabled: true, type: 'PK', freq: 4000, gain: 4.0, q: 2.2 },
      { id: '5', enabled: true, type: 'HS', freq: 11000, gain: -3.0, q: 0.71 },
    ],
  },
  {
    id: 'cinema-imax-immersion',
    name: 'Cinéma IMAX & Série Dolby Experience',
    brand: 'Genres & Gaming',
    category: 'cinema',
    description: 'Sous-basses profondes de salle obscure, dialogues détachés et dynamique surround.',
    mode: 'parametric',
    preamp: -5.5,
    bassBoost: 4.5,
    crossfeed: true,
    parametricFilters: [
      { id: '1', enabled: true, type: 'LS', freq: 60, gain: 6.5, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 220, gain: -2.0, q: 1.41 },
      { id: '3', enabled: true, type: 'PK', freq: 1800, gain: 3.0, q: 1.6 },
      { id: '4', enabled: true, type: 'HS', freq: 10000, gain: 2.5, q: 0.71 },
    ],
  },
  {
    id: 'utility-podcast-voice',
    name: 'Podcast & Conférences Claires (Filtre Coupe-Bruit)',
    brand: 'Genres & Gaming',
    category: 'utility',
    description: 'Coupe les grondements de micro et accentue l’intelligibilité de la parole.',
    mode: 'parametric',
    preamp: -2.0,
    parametricFilters: [
      { id: '1', enabled: true, type: 'HP', freq: 90, gain: 0, q: 0.71 },
      { id: '2', enabled: true, type: 'PK', freq: 300, gain: -2.5, q: 1.41 },
      { id: '3', enabled: true, type: 'PK', freq: 2500, gain: 3.8, q: 1.8 },
      { id: '4', enabled: true, type: 'HS', freq: 10000, gain: -2.0, q: 0.71 },
    ],
  },
];
